name = "RayTraceHeatTransfer"
uuid = "7cf1493d-886e-405c-b582-53b49fa147b6"
authors = ["Nikolaj Maack Bielefeld"]
version = "1.0.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
